spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: boot-swagger-starter
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.geo.integrated.dao
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 填入注册后得到的accessKey和accessSecretKey
qiniu:
  accessKey: wTX9kW-E_esb7jKODHzulGonErVrle_LhR5_r8fU
  accessSecretKey: M4Fpizzp_gu13a-EXQfsu078ptHdkAM48x2-kfi3
  bucketName: geo-integrated
  domainName: http://rpppj5gw9.hb-bkt.clouddn.com/

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Geo  #JWT负载中拿到开头