server:
  address: xxx.xxx.xxx.xxx
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/geo_integrated?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: pDWP5Xi+pPQ7W78rw2xYLTE5qOdk6p+4g8VPOSUrdZHbckUhmJIrrPRW81lX/VOLIyK9e1qF89UBUy9x/K7egw==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK7n4hdG4inyggm99S6HxCfuEGzLob0DplBKFbxROLveFXMEOLJ1b+BA/58qVLkh795Zn/c0V1PWmFklC/zG4u8CAwEAAQ==
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置连接池
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 获取连接时最大等待时间(单位：毫秒)
      max-wait: 60000
      # 配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      filters: stat, wall
      # 配置监控页功能
      stat-view-servlet:
        url-pattern: /druid/*
        allow: localhost,127.0.0.1
        # 是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        enabled: true
        # 登录用户名/密码
        login-username: admin
        login-password: 123456
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
      # 监控web
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
      filter:
        # 对上面filters里面的stat的详细配置
        stat:
          slow-sql-millis: 1000
          enabled: true
          log-slow-sql: true
        # 对上面filters里面的wall的详细配置
        wall:
          enabled: true
          config:
            drop-table-allow: false
  redis:
    host: xxx.xxx.xxx.xxx # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

# 自定义redis key
redis:
  key:
    expire:
      authCode: 120 # 验证码超期时间

logging:
  level:
    root: info
    com.geo.integrated: debug
  file:
    name: backend/log-prod/log-prod

# Swagger配置
swagger:
  # 是否开启swagger
  enable: false