spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.geo.integrated.dao
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl