spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: boot-swagger-starter

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.geo.integrated.dao
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl